apiVersion: apps/v1
kind: Deployment
metadata:
  name: asciiartify-web
  labels:
    app: asciiartify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asciiartify-web
  template:
    metadata:
      labels:
        app: asciiartify-web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web
          configMap:
            name: asciiartify-web
            items:
              - key: index.html
                path: index.html
