apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asciiartify
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mexxo-dvp/AsciiArtify.git
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
